SELECT NOMECAVALO, NOMPROVA, COLOCACAO, ANO FROM CAVALO, PROVA, DISPUTA WHERE 
DISPUTA.CODCAVALO = CAVALO.CODCAVALO AND
DISPUTA.CODPROVA = PROVA.CODPROVA AND
PROVA.NOMPROVA = 'GP Bento Goncalves' AND
DISPUTA.COLOCACAO = 1;
