--CRIA TABELA FUNCIONARIO--
CREATE TABLE FUNCIONARIO (
    CODFUNC INT, 
    NOMFUNC VARCHAR(50), 
    CODCHEFE INT, PRIMARY KEY(CODFUNC), 
    FOREIGN KEY(CODCHEFE) REFERENCES FUNCIONARIO(CODFUNC)
);

--INSERE VALOES NA TABELA--
INSERT INTO FUNCIONARIO (CODFUNC, NOMFUNC, CODCHEFE) VALUES (40, 'Chefao', NULL);
INSERT INTO FUNCIONARIO (CODFUNC, NOMFUNC, CODCHEFE) VALUES (30, 'FULANO', 40);
INSERT INTO FUNCIONARIO (CODFUNC, NOMFUNC, CODCHEFE) VALUES (20, 'SICLANO', 40);
INSERT INTO FUNCIONARIO (CODFUNC, NOMFUNC, CODCHEFE) VALUES (10, 'BELTRANO', 30);

--MOSTRA TUDO--
SELECT * FROM FUNCIONARIO;

--MOSTRA O NOME DO FUNCIONARIO E DO CHEFE--
SELECT CHEFE.NOMFUNC, FUNCIONARIO.NOMFUNC FROM FUNCIONARIO, FUNCIONARIO AS CHEFE WHERE
FUNCIONARIO.CODCHEFE = CHEFE.CODFUNC;
