SELECT * FROM CAVALO;
SELECT * FROM PROVA;
SELECT * FROM DISPUTA;
--NOT EXISTS--
SELECT NOMECAVALO FROM CAVALO WHERE  NOT EXISTS (SELECT DISPUTA FROM DISPUTA WHERE CAVALO.CODCAVALO = DISPUTA.CODCAVALO);

--NOT IN--
SELECT NOMECAVALO FROM CAVALO WHERE  CODCAVALO NOT IN (SELECT CODCAVALO FROM DISPUTA);
