CREATE TABLE TABELA (COD INT, VAL1 INT, VAL2 INT, PRIMARY KEY(COD));

--criar visao--
CREATE VIEW VISAO1 AS SELECT COD, VAL1 FROM TABELA;

--inserir dados--
INSERT INTO TABELA VALUES (1, 1, 1);
INSERT INTO TABELA VALUES (2, 2, 2);
INSERT INTO TABELA VALUES (3, 3, 3);
INSERT INTO TABELA VALUES (4, 4, 4);

--chamar visao--
SELECT * FROM VISAO1;
