DELETE FROM TABELA;
SELECT * FROM TABELA;

-- NAO DEIXA TRABALHAR COM UM COD QUE ELE NAO PODERA VER --
-- NO CASO <= 3 --
CREATE VIEW VISAO4 AS SELECT * FROM TABELA WHERE COD > 3 WITH CHECK OPTION;

-- POR ISSO NAO FUNCIONA ESSE INSERT NA VISAO --
INSERT INTO VISAO4 (COD, VAL1, VAL2) values (1,10,100);

-- AQUI FUNCIONA --
INSERT INTO VISAO4 (COD, VAL1, VAL2) values (4,10,100);

SELECT * FROM VISAO4;

-- CRIA A VISAO MAS NAO CHECK NO MOMENTO DE INSERIR --
-- INSERE UMA LINHA QUE ELE NAO VE --
CREATE VIEW VISAO5 AS SELECT * FROM TABELA WHERE COD > 3 ;

INSERT INTO VISAO5 (COD, VAL1, VAL2) values (4,10,100);
INSERT INTO VISAO5 (COD, VAL1, VAL2) values (1,10,100);

SELECT * FROM VISAO5;
