CREATE TABLE EMPREGADO(CODEMP INT, NOMEEMP CHAR(50),PRIMARY KEY(CODEMP));
CREATE TABLE MOTORISTA(CODMOT INT, CNH CHAR(10), PRIMARY KEY(CODMOT), FOREIGN KEY(CODMOT) REFERENCES EMPREGADO(CODEMP));
CREATE TABLE ENGENHEIRO(CODENG INT, CREA CHAR(10), PRIMARY KEY(CODENG), FOREIGN KEY(CODENG) REFERENCES EMPREGADO(CODEMP));
