SELECT NOMFORNEC FROM FORNECEDOR WHERE CODFORNEC NOT IN 
(SELECT CODFORNEC FROM FORNECE, PRODUTO, TIPO WHERE 
FORNECE.CODPROD = PRODUTO.CODPROD
AND PRODUTO.CODTIPO = TIPO.CODTIPO
AND NOMTIPO = 'BRINQUEDOS');
