SELECT NOMCLI, NOMPROD
FROM CLIENTE, COMPRA, ITEM_COMPRA, PRODUTO 
WHERE CLIENTE.CODCLI = COMPRA.CODCLI
AND COMPRA.CODCOMPRA = ITEM_COMPRA.CODCOMPRA
AND ITEM_COMPRA.CODCOMPRA = PRODUTO.CODPROD
ORDER BY NOMCLI;
