SELECT CRIADOR.CODCRIADOR, NOMECRIADOR, COUNT(*), AVG(VALOR), SUM(VALOR), MAX(VALOR), MIN(VALOR) FROM CAVALO, CRIADOR WHERE 
CAVALO.CODCRIADOR = CRIADOR.CODCRIADOR GROUP BY
NOMECRIADOR, CRIADOR.CODCRIADOR;
