CREATE OR REPLACE FUNCTION turmasProf(CODIGO INT) 
RETURNS INT
AS $$
DECLARE NUMERODETURMAS INT;
BEGIN
	SELECT COUNT(*) FROM TURMA INTO NUMERODETURMAS WHERE TURMA.CODPROF = CODIGO;
	RETURN NUMERODETURMAS;
END;
$$ LANGUAGE 'plpgsql';

SELECT turmasProf(1);
