SELECT NOMEEST, NOMEPRODUTO FROM ESTANDE, ESTANDE_PRODUTO, PRODUTO WHERE
ESTANDE.CODEST = ESTANDE_PRODUTO.CODEST
AND
ESTANDE_PRODUTO.CODPRODUTO = PRODUTO.CODPRODUTO;

SELECT NOMEEST, NOMEPRODUTO, VALOR FROM ESTANDE, ESTANDE_PRODUTO, PRODUTO WHERE
ESTANDE.CODEST = ESTANDE_PRODUTO.CODEST
AND
ESTANDE_PRODUTO.CODPRODUTO = PRODUTO.CODPRODUTO;
