SELECT NOMVINHO, NOMREV, DATA_LEVANTAMENTO, VALOR_LEVANTAMENTO FROM 
VINHO, REVENDEDOR, VENDE WHERE
VINHO.CODVINHO = VENDE.CODVINHO AND
VENDE.CODREV = REVENDEDOR.CODREV AND
DATA_LEVANTAMENTO = '20/11/2012';
