CREATE TABLE CURSO(CODCURSO INT, NOMECURSO VARCHAR(50), PRIMARY KEY(CODCURSO));
CREATE TABLE ALUNO (CODALUNO INT, NOMEALUNO VARCHAR(50), CODCURSO INT, PRIMARY KEY(CODALUNO), FOREIGN KEY(CODCURSO) REFERENCES CURSO(CODCURSO));

INSERT INTO CURSO VALUES (1, 'curso 1');
INSERT INTO CURSO VALUES (2, 'curso 2');
INSERT INTO CURSO VALUES (3, 'curso 3');
INSERT INTO CURSO VALUES (4, 'curso 4');

INSERT INTO ALUNO VALUES (1, 'aluno 1', 2);
INSERT INTO ALUNO VALUES (2, 'aluno 2', 3);
INSERT INTO ALUNO VALUES (3, 'aluno 3', 2);
INSERT INTO ALUNO VALUES (4, 'aluno 4', 1);
INSERT INTO ALUNO VALUES (5, 'aluno 5', 1);

--EX: MOSTRAR OS ALUNOS QUE NAO ESTAO EM NENHUM CURSO
--NOT EXISTS
SELECT NOMECURSO FROM CURSO WHERE NOT EXISTS(SELECT * FROM ALUNO WHERE ALUNO.CODCURSO = CURSO.CODCURSO);
SELECT NOMECURSO FROM CURSO WHERE EXISTS(SELECT * FROM ALUNO WHERE ALUNO.CODCURSO = CURSO.CODCURSO);


